---
title: "Improper Type Errors"
output: html_notebook
---

```{r setup, echo = FALSE}
library(dplyr)
library(readr)
library(tidyr)  
library(xtable)

options(dplyr.summarise.inform = FALSE)

all_path <- file.path("../all.csv")
all <- read_csv(
    all_path,
    show_col_types = FALSE
)
finished_early_path <- file.path("../locations/finished_early.csv")
finished_early <- read_csv(
    finished_early_path,
    show_col_types = FALSE
)
finished_late_path <- file.path("../locations/finished_late.csv")
finished_late <- read_csv(
    finished_late_path,
    show_col_types = FALSE
)
foreign_abis_path <- file.path("../locations/foreign_module_abis.csv")
foreign_abis <- read_csv(
    foreign_abis_path,
    show_col_types = FALSE
) %>% filter(abi == "C")
einfo_path <- file.path("../locations/error_info.csv")
einfo <- read_csv(
    einfo_path,
    show_col_types = FALSE
)
eloc_path <- file.path("../locations/error_locations.csv")
eloc <- read_csv(
    eloc_path,
    show_col_types = FALSE
)

discriminant_counts_path <- file.path("../locations/category_error_counts.csv")
discriminant_counts <- read_csv(
    discriminant_counts_path,
    show_col_types = FALSE
) %>% inner_join(einfo, by = c("err_id", "crate_name"))

discriminant_names_path <- file.path("../discriminants.csv")
discriminant_names <- read_csv(
    discriminant_names_path,
    show_col_types = FALSE
)

reasons_path <- file.path("../reasons.csv")
reasons <- read_csv(
    reasons_path,
    show_col_types = FALSE
)
```
```{r include = FALSE}
discriminant_counts %>%
  group_by(crate_name, category) %>%
  summarize(num_errs = sum(count)) %>% 
  group_by(category) %>% 
  summarize(
    num_crates = n(), 
    mean_errs = mean(num_errs), 
    max_errs = max(num_errs), 
    min_errs = min(num_errs), 
    stdev_errs = sd(num_errs)
  )

unique_errors <- einfo %>% 
  select(discriminant, err_text) %>% 
  unique %>% 
  nrow
```
We observed `r sum(discriminant_counts$count)` type errors in foreign bindings. There were `r unique_errors` unique errors.
```{r echo = FALSE}

process_counts <- function(df) {
  df %>% group_by(crate_name, category) %>%
    summarize(num_errors = sum(count)) %>%
    group_by(category)
}

count_summary_all <- discriminant_counts %>%
  process_counts %>%
  summarize(
    n_crates_all = n(),
    errs_all = sum(num_errors),
    mean_errs_all = round(mean(num_errors), 1),
    stdev_errs_all = round(sd(num_errors), 1),
    max_errs_all = max(num_errors)
  )

unique_all <- discriminant_counts %>% select(crate_name, category, discriminant, reason, abi, err_text, ignored) %>%
  group_by(category) %>% unique %>% summarize(n_unique_all=n())
unique_ignored <- discriminant_counts %>% select(crate_name, category, discriminant, reason, abi, err_text, ignored) %>%
  group_by(category) %>% filter(ignored == TRUE) %>% unique %>% summarize(n_unique_ign=n())

count_summary_ign <-discriminant_counts %>% 
  filter(ignored == TRUE) %>%
  process_counts %>%
  summarize(
    n_crates_ign = n(),
    errs_ign = sum(num_errors),
    mean_errs_ign = round(mean(num_errors), 1),
    stdev_errs_ign = round(sd(num_errors), 1),
    max_errs_ign = max(num_errors)
  )
count_summary <- count_summary_all %>% inner_join(count_summary_ign, by=("category"))
count_summary$n_crates <- paste(count_summary_all$n_crates_all, "/", count_summary_ign$n_crates_ign)
count_summary$n_errs <- paste(count_summary_all$errs_all, "/", count_summary_ign$errs_ign)
count_summary$mean_errs <- paste(count_summary_all$mean_errs_all, "/", count_summary_ign$mean_errs_ign)
count_summary$stdev_errs <- paste(count_summary_all$stdev_errs_all, "/", count_summary_ign$stdev_errs_ign)
count_summary$max_errs <- paste(count_summary_all$max_errs_all, "/", count_summary_ign$max_errs_ign)

count_summary <- count_summary %>% inner_join(unique_all, by=("category"))
count_summary <- count_summary %>% inner_join(unique_ignored, by=("category"))
count_summary$n_unique <- paste(count_summary$n_unique_all, "/", count_summary$n_unique_ign)

count_summary <- count_summary %>% select(category, n_crates, n_unique, n_errs, mean_errs, stdev_errs, max_errs)

colnames(count_summary) <- c("Category", "# Crates", "# Unique Errors", "Total", "Mean", "St.Dev", "Max")
count_summary
```


```{r echo = FALSE}
named_counts <- discriminant_counts %>% 
  inner_join(discriminant_names, by=c("discriminant")) %>% filter(ignored == TRUE)

decls <- named_counts %>% filter(category %in% c("foreign_functions"))
defns <- named_counts %>% filter(category %in% c("rust_functions"))
decls_items <- named_counts %>% filter(category %in% c("static_items"))

discrim_counts <- einfo %>% 
  select(reason, discriminant, err_text) %>% 
  unique %>% 
  group_by(reason, discriminant) %>% 
  summarize(n_unique=n())

decls_items_counts <- 
  decls_items %>% 
  group_by(reason, type_name) %>% 
  summarize(fi_count = sum(count)) %>% 
  unique

decls_counts <- decls %>% 
  group_by(reason, type_name) %>% 
  summarize(ff_count = sum(count)) %>% 
  unique

defns_counts <- defns %>% 
  group_by(reason, type_name) %>% 
  summarize(ef_count = sum(count)) %>% 
  unique

final <- discriminant_names %>% 
  left_join(decls_counts, by=c("type_name")) %>% 
  left_join(decls_items_counts, by=c("type_name","reason")) %>% 
  left_join(defns_counts, by=c("type_name", "reason")) %>% 
  left_join(discrim_counts, by=c("discriminant", "reason")) %>% 
  inner_join(reasons, by=c("reason")) %>%
  mutate(across(where(is.numeric), ~ replace_na(.x, 0))) %>% 
  select(type_name, reason_name, n_unique, ff_count, fi_count, ef_count)

final$total_occurrences <- final$ff_count + final$fi_count + final$ef_count
filtered <- final %>% filter(total_occurrences > 0) %>% arrange(type_name)

colnames(filtered) <- c("Type", "Error", "Foreign Functions", "Foreign Items", "Rust Functions", "Total", "Unique")

filtered

```

```{r}

large <- function(x){
  paste0('{\\bfseries ', x, '}')
}
addtorow <- list()
addtorow$pos <- list(0, 0)
addtorow$command <- c("& & & \\multicolumn{4}{c}{# Occurrences} \\\\\n",
"Category & # Crates & # Unique & Total & Mean & St.Dev. & Max \\\\\n")
xt_counts = xtable(
  count_summary, 
  type = "latex", 
  digits=c(0,0,0,0,0,1,1,0),
  caption= "Summary statistics for improper type error occurrences. The number to the left of the '/' corresponds to all error occurrences, while the number to the right corresponds to hidden error occurrences.",
  label = "table:error_summary"
)

align(xt_counts) <- "llcccccc"
print(xt_counts, 
      include.rownames = FALSE,
      add.to.row = addtorow, 
      file = "../latex/err_counts.tex",
      include.colnames = FALSE,
      sanitize.colnames.function = large
)

addtorow <- list()
addtorow$pos <- list(0, 0)
addtorow$command <- c("& & & \\multicolumn{4}{c}{# Hidden Occurrences} \\\\\n",
"Type & Error & # Unique & Foreign Functions & Foreign Items & Rust Functions & Total \\\\\n")
xt_type_counts <- xtable(
  filtered, 
  type = "latex", 
  digits=c(0,0,0,0,0,0,0,0),
  caption= "Summary of hidden improper type errors for each data type.",
  label = "table:error_type_counts"
)
align(xt_type_counts) <- "lllccccc"
print(xt_type_counts, 
      include.rownames = FALSE,
      add.to.row = addtorow, 
      file = "../latex/err_type_counts.tex",
      include.colnames = FALSE,
      sanitize.colnames.function = large
    )



```